# Generated by Django 6.0.2 on 2026-02-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('opt1', models.TextField()),
                ('opt2', models.TextField()),
                ('opt3', models.TextField()),
                ('opt4', models.TextField()),
                ('correct_opt', models.TextField()),
                ('exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
