# Generated by Django 6.0.2 on 2026-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('other', 'Other (MP Exams - Default)'), ('neet', 'NEET')], default='other', help_text='NEET questions are shown only to NEET students', max_length=10),
        ),
    ]
