# Generated by Django 6.0.2 on 2026-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_type',
            field=models.CharField(choices=[('other', 'Other (MP Exams - Default)'), ('neet', 'NEET')], default='other', help_text='NEET students see NEET questions, Others see default MP exam questions', max_length=10),
        ),
    ]
